// <auto-generated/>
using Microsoft.AspNetCore.Components;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature.GameSave;

namespace ResourceTrackerUI.Features.GameSave
{
    public partial class EditGameSaveModal
    {
        [CascadingParameter] 
        private IMudDialogInstance MudDialog { get; set; }

        [Inject] 
        private IGameSaveService GameSaveService { get; set; }
        [Inject] 
        private IGameService GameService { get; set; }
        [Inject] 
        private ISnackbar Snackbar { get; set; }

        [Parameter] 
        public GameSaveModel Model { get; set; } = new();
        [Parameter] 
        public FormModeEnum FormMode { get; set; }

        private async Task Submit()
        {
            switch (FormMode)
            {
                case FormModeEnum.Create:
                    await GameSaveService.CreateGameSave(Model, appCancellation.Token);
                    break;
                case FormModeEnum.Update:
                    await GameSaveService.UpdateGameSave(Model, appCancellation.Token);
                    break;
                case FormModeEnum.Delete:
                    await GameSaveService.DeleteGameSave(Model.Id, appCancellation.Token);
                    break;
            }

            MudDialog.Close();
        }

        private void Cancel() => MudDialog.Cancel();

        private async Task<IEnumerable<object>> OnGameDataLoad()
        {
            var data = await GameService.SearchGame(
                new() { PageSize = int.MaxValue, OrderBy = "Id" },
                appCancellation.Token);
            return data.Data.ToList();
        }
    }
}