// <auto-generated/>
using Microsoft.AspNetCore.Components;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Application.Services.Common;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature.Game;
using ResourceTrackerUI.Domain.Models.Feature.GameSave;

namespace ResourceTrackerUI.Features.GameSave
{
    public partial class SwitchGameSaveModal
    {
        [CascadingParameter]
        private IMudDialogInstance MudDialog { get; set; }

        [Inject]
        private IGameService GameService { get; set; }

        [Inject]
        private IGameSaveService GameSaveService { get; set; }

        [Inject]
        private GameSaveState GameSaveState { get; set; }

        [Inject]
        private ISnackbar Snackbar { get; set; }

        // Current active save id — passed in from caller so we can highlight it
        [Parameter]
        public int? CurrentSaveId { get; set; }

        // ── State ──
        private int _step = 1;
        private bool _isLoading = false;
        private string _searchString = string.Empty;

        // Step 1
        private List<SearchGamesResponseModel> _games = new();
        private SearchGamesQueryModel _searchModel = new();
        private SearchGamesResponseModel _selectedGame;

        // Step 2
        private List<GameSaveListModel> _saves = new();

        protected override async Task OnInitializedAsync()
        {
            _searchModel = new SearchGamesQueryModel
            {
                OrderBy = "Id",
                OrderDirection = OrderDirectionEnum.Descending,
                PageSize = int.MaxValue
            };

            await LoadGames();
        }

        // ── Step 1 ──

        private async Task LoadGames()
        {
            _isLoading = true;
            var response = await GameService.SearchGame(_searchModel, appCancellation.Token);
            _games = response.Data.ToList();
            _isLoading = false;
            await InvokeAsync(StateHasChanged);
        }

        private async Task OnGameSearch(string text)
        {
            _searchModel.SearchTerms = text;
            await LoadGames();
        }

        private async Task SelectGame(SearchGamesResponseModel game)
        {
            _selectedGame = game;
            _step = 2;
            await LoadSavesForGame(game.Id);
        }

        // ── Step 2 ──

        private async Task LoadSavesForGame(int gameId)
        {
            _isLoading = true;
            StateHasChanged();

            var result = await GameSaveService.GetGameSavesForGame(gameId, appCancellation.Token);
            _saves = result.ToList(); 

            _isLoading = false;
            StateHasChanged();
        }

        private async Task ConfirmSave(GameSaveListModel save)
        {

            await GameSaveState.SetActiveSave(save.Id, _selectedGame.Id, _selectedGame.Name, save.Name, _selectedGame.ImageUrl);
            Snackbar.Add($"Active save set to {save.Name}", Severity.Success);
            MudDialog.Close(DialogResult.Ok(save.Id));
        }

        private void GoBack()
        {
            _step = 1;
            _saves = new();
            _selectedGame = null;
            StateHasChanged();
        }

        private void Cancel() => MudDialog.Cancel();
    }
}