// <auto-generated/>
using MapsterMapper;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Application.Services.Common;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature;
using ResourceTrackerUI.Domain.Models.Feature.Inventory;
using ResourceTrackerUI.Domain.Models.Feature.InventorySummary;
using ResourceTrackerUI.Domain.Models.Feature.Quest;
using ResourceTrackerUI.Features.Quest;

namespace ResourceTrackerUI.Features.Inventory
{
    public partial class Index
    {
        [Inject]
        private IQuestService QuestService { get; set; }
        [Inject]
        private IDialogService DialogService { get; set; }
        [Inject]
        private ISnackbar Snackbar { get; set; }
        [Inject]
        private GameSaveState GameSaveState { get; set; }

        [Inject]
        private IMapper Mapper { get; set; }

        // ── View state ──
        private string _view = "location";
        private bool _isLoading = false;
        // ── Data ──
        private List<SearchQuestsResponseModel> _quests { get; set; } = new List<SearchQuestsResponseModel>();

        // Aggregated view
        private InventorySummaryComponent _inventorySummary { get; set; }


        protected override async Task OnInitializedAsync()
        {
            if (!GameSaveState.HasActiveSave) return;
            await LoadQuests();
        }

        private async Task LoadQuests()
        {
            _isLoading = true;

            var response = await QuestService.SearchQuest(new SearchQuestsQueryModel
            {
                GameSaveId = GameSaveState.ActiveGameSaveId,
                PageSize = int.MaxValue,
                OrderBy = "Id"
            }, appCancellation.Token);

            _quests = response.Data.ToList();

            _isLoading = false;
        }

        private void SetView(string view)
        {
            _view = view;
            StateHasChanged();
        }


        // ── Quest modals ──

        private async Task OpenCreateQuestModal()
        {
            var model = new QuestModel { GameSaveId = GameSaveState.ActiveGameSaveId!.Value };

            var parameters = new DialogParameters<EditQuestModal>
            {
                { x => x.Model, model },
                { x => x.FormMode, FormModeEnum.Create }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditQuestModal>(FormModeEnum.Create.ToString(), parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled)
            {
                var resposne = result.Data as QuestModel;
                if (resposne != null)
                {
                    var quest = Mapper.Map<SearchQuestsResponseModel>(resposne);
                    _quests.Add(quest);
                }
            }
        }

        private void QuestDataUpdate(QuestUpdatedModel model)
        {
            switch (model.UpdateType)
            {
                case QuestUpdateTypeEnum.InitiatedQuestItems:
                    break;
                case QuestUpdateTypeEnum.QuestDeleted:
                case QuestUpdateTypeEnum.ItemsUpdated:
                    _inventorySummary?.LoadData();
                    break;
            }
            StateHasChanged();
        }

       
    }
}