// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature.Quest;

namespace ResourceTrackerUI.Components.PageComponents.feature
{
    public partial class EditQuestModal
    {
        [CascadingParameter] private IMudDialogInstance MudDialog { get; set; }
        [Inject] private IQuestService QuestService { get; set; }
        [Inject] private ISnackbar Snackbar { get; set; }

        [Parameter] 
        public QuestModel Model { get; set; } = new();
        [Parameter] 
        public FormModeEnum FormMode { get; set; }

        private async Task Submit()
        {
            switch (FormMode)
            {
                case FormModeEnum.Create: 
                    await QuestService.CreateQuest(Model, appCancellation.Token); break;
                case FormModeEnum.Update: 
                    await QuestService.UpdateQuest(Model, appCancellation.Token); break;
                case FormModeEnum.Delete: 
                    await QuestService.DeleteQuest(Model.Id, appCancellation.Token); break;
            }
            MudDialog.Close(Model);
        }

        private void Cancel() => MudDialog.Cancel();
    }
}