// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Application.Services.Common;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature.Components;
using ResourceTrackerUI.Domain.Models.Feature.Inventory;

namespace ResourceTrackerUI.Components.PageComponents.feature
{
    public partial class EditInventoryItemModal
    {
        [CascadingParameter] 
        private IMudDialogInstance MudDialog { get; set; }
        [Inject] 
        private IInventoryService InventoryService { get; set; }
        [Inject] 
        private IComponentService ComponentService { get; set; }
        [Inject] 
        private ISnackbar Snackbar { get; set; }
        [Inject] 
        private GameSaveState GameSaveState { get; set; }

        [Parameter] 
        public InventoryModel Model { get; set; } = new();
        [Parameter] 
        public FormModeEnum FormMode { get; set; }

        private async Task Submit()
        {
            switch (FormMode)
            {
                case FormModeEnum.Create: 
                    await InventoryService.CreateInventory(Model, appCancellation.Token); break;
                case FormModeEnum.Update: 
                    await InventoryService.UpdateInventory(Model, appCancellation.Token); break;
                case FormModeEnum.Delete: 
                    await InventoryService.DeleteInventory(Model.Id, appCancellation.Token); break;
            }
            MudDialog.Close();
        }

        private void Cancel() => MudDialog.Cancel();

        private async Task<IEnumerable<object>> OnComponentDataLoad()
        {
            var data = await ComponentService.SearchComponent(new SearchComponentQueryModel
            {
                PageSize = int.MaxValue,
                OrderBy = "Name",
                GameId = GameSaveState.ActiveGameId
            }, appCancellation.Token);
            return data.Data.ToList();
        }
    }
}