// <auto-generated/>
using Microsoft.AspNetCore.Components;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Application.Services.Common;
using ResourceTrackerUI.Components.PageComponents.feature;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature.Game;
using ResourceTrackerUI.Domain.Models.Feature.GameSave;

namespace ResourceTrackerUI.Pages.feature
{
    public partial class GameSave
    {
        [Inject] 
        private IGameService GameService { get; set; }
        [Inject] 
        private IGameSaveService GameSaveService { get; set; }
        [Inject] 
        private IDialogService DialogService { get; set; }
        [Inject] 
        private ISnackbar Snackbar { get; set; }
        [Inject] 
        private GameSaveState GameSaveState { get; set; }

        private List<SearchGamesResponseModel> _games = new();
        private Dictionary<int, List<GameSaveListModel>> _savesPerGame = new();
        private HashSet<int> _expandedGameIds = new();
        private HashSet<int> _loadingSaveIds = new();
        private bool _isLoading = false;

        protected override async Task OnInitializedAsync()
        {
            _isLoading = true;
            var response = await GameService.SearchGame(new SearchGamesQueryModel
            {
                OrderBy = "Id",
                PageSize = int.MaxValue
            }, appCancellation.Token);

            _games = response.Data.ToList();
            _isLoading = false;

            // Auto-expand the game that owns the current active save
            if (GameSaveState.HasActiveSave)
            {
                var activeGame = _games.FirstOrDefault(g => g.Name == GameSaveState.ActiveGameName);
                if (activeGame != null)
                    await ExpandGame(activeGame.Id);
            }
        }

        private async Task ToggleGame(int gameId)
        {
            if (_expandedGameIds.Contains(gameId))
                _expandedGameIds.Remove(gameId);
            else
                await ExpandGame(gameId);
        }

        private async Task ExpandGame(int gameId)
        {
            _expandedGameIds.Add(gameId);

            if (!_savesPerGame.ContainsKey(gameId))
            {
                _loadingSaveIds.Add(gameId);
                StateHasChanged();

                var result = await GameSaveService.GetGameSavesForGame(gameId, appCancellation.Token);
                _savesPerGame[gameId] = result.ToList();

                _loadingSaveIds.Remove(gameId);
                StateHasChanged();
            }
        }

        private async Task SetActiveSave(GameSaveListModel save, SearchGamesResponseModel game)
        {
            await GameSaveState.SetActiveSave(save.Id, game.Id, game.Name, save.Name, game.ImageUrl);
            Snackbar.Add($"Active save set to {save.Name}", Severity.Success);
            StateHasChanged();
        }

        // ── Modals ──

        private Task OpenCreateModal() => OpenCreateModalForGame(null);

        private async Task OpenCreateModalForGame(SearchGamesResponseModel? game)
        {
            var model = new GameSaveModel { GameId = game?.Id ?? 0 };

            var parameters = new DialogParameters<EditGameSaveModal>
            {
                { x => x.Model, model },
                { x => x.FormMode, FormModeEnum.Create }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditGameSaveModal>("Create Save", parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled && model.GameId > 0)
            {
                // Refresh saves for that game if it's expanded
                _savesPerGame.Remove(model.GameId);
                if (_expandedGameIds.Contains(model.GameId))
                    await ExpandGame(model.GameId);
            }
        }

        private async Task OpenEditModal(GameSaveListModel save, SearchGamesResponseModel game)
        {
            var fullSave = await GameSaveService.GetGameSave(save.Id, appCancellation.Token);

            var parameters = new DialogParameters<EditGameSaveModal>
            {
                { x => x.Model, fullSave },
                { x => x.FormMode, FormModeEnum.Update }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditGameSaveModal>("Edit Save", parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled)
            {
                _savesPerGame.Remove(game.Id);
                await ExpandGame(game.Id);
            }
        }

        private async Task OpenDeleteModal(GameSaveListModel save, SearchGamesResponseModel game)
        {
            var fullSave = await GameSaveService.GetGameSave(save.Id, appCancellation.Token);

            var parameters = new DialogParameters<EditGameSaveModal>
            {
                { x => x.Model, fullSave },
                { x => x.FormMode, FormModeEnum.Delete }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditGameSaveModal>("Delete Save", parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled)
            {
                // If deleted save was the active one, clear state
                if (fullSave.Id == GameSaveState.ActiveGameSaveId)
                    GameSaveState.ClearActiveSave();

                _savesPerGame.Remove(game.Id);
                await ExpandGame(game.Id);
            }
        }
    }
}
