// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Application.Services.Common;
using ResourceTrackerUI.Components.PageComponents.feature;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature;
using ResourceTrackerUI.Domain.Models.Feature.Inventory;
using ResourceTrackerUI.Domain.Models.Feature.Quest;

namespace ResourceTrackerUI.Pages.feature
{
    public partial class Inventory
    {
        [Inject] private IQuestService QuestService { get; set; }
        [Inject] private IInventoryService InventoryService { get; set; }
        [Inject] private IDialogService DialogService { get; set; }
        [Inject] private ISnackbar Snackbar { get; set; }
        [Inject] private GameSaveState GameSaveState { get; set; }

        // ── View state ──
        private string _view = "location";
        private bool _isLoading = false;
        private string _aggregateSearch = string.Empty;

        // ── Data ──
        private List<SearchQuestsResponseModel> _quests { get; set; } = new List<SearchQuestsResponseModel>();
        private Dictionary<int, List<SearchInventoryResponseModel>> _itemsPerQuest = new();
        private HashSet<int> _expandedQuestIds = new();
        private HashSet<int> _loadingQuestIds = new();
        private Dictionary<int, string> _searchPerQuest = new();

        // Aggregated view
        private List<AggregatedInventoryItem> _aggregated = new();
        private int _totalItemsLoaded => _itemsPerQuest.Values.Sum(x => x.Count);

        private IEnumerable<AggregatedInventoryItem> FilteredAggregated =>
            string.IsNullOrWhiteSpace(_aggregateSearch)
                ? _aggregated
                : _aggregated.Where(x =>
                    x.ComponentName.Contains(_aggregateSearch, StringComparison.OrdinalIgnoreCase) ||
                    x.ComponentType.Contains(_aggregateSearch, StringComparison.OrdinalIgnoreCase));

        protected override async Task OnInitializedAsync()
        {
            if (!GameSaveState.HasActiveSave) return;
            await LoadQuests();
        }

        private async Task LoadQuests()
        {
            _isLoading = true;

            var response = await QuestService.SearchQuest(new SearchQuestsQueryModel
            {
                GameSaveId = GameSaveState.ActiveGameSaveId,
                PageSize = int.MaxValue,
                OrderBy = "Id"
            }, appCancellation.Token);

            _quests = response.Data.ToList();

            // Init search dict for each quest
            foreach (var q in _quests)
                _searchPerQuest.TryAdd(q.Id, string.Empty);

            _isLoading = false;

            // Load ALL items upfront for aggregate view
            await LoadAllItemsForAggregate();
        }

        // Loads every quest's items for the aggregate totals view
        private async Task LoadAllItemsForAggregate()
        {
            foreach (var quest in _quests)
            {
                if (!_itemsPerQuest.ContainsKey(quest.Id))
                    await LoadItemsForQuest(quest.Id);
            }

            BuildAggregated();
            StateHasChanged();
        }

        private async Task LoadItemsForQuest(int questId)
        {
            _loadingQuestIds.Add(questId);
            StateHasChanged();

            var response = await InventoryService.SearchInventory(new SearchInventoryQueryModel
            {
                QuestId = questId,
                PageSize = int.MaxValue,
                OrderBy = "ComponentName"
            }, appCancellation.Token);

            _itemsPerQuest[questId] = response.Data.ToList();
            _loadingQuestIds.Remove(questId);
        }

        private void BuildAggregated()
        {
            _aggregated = _itemsPerQuest
                .SelectMany(kvp => kvp.Value.Select(item => new { QuestId = kvp.Key, Item = item }))
                .GroupBy(x => x.Item.Id)
                .Select(g => new AggregatedInventoryItem
                {
                    ComponentId = g.Key,
                    ComponentName = g.First().Item.ComponentName,
                    ComponentType = g.First().Item.ComponentTypeName,
                    ComponentImageUrl = g.First().Item.ComponentImageUrl,
                    TotalQuantity = g.Sum(x => x.Item.AmountAquired),
                    Locations = g.Select(x => new AggregatedLocation
                    {
                        QuestId = x.QuestId,
                        QuestName = _quests.FirstOrDefault(q => q.Id == x.QuestId)?.Name ?? "",
                        Quantity = x.Item.AmountAquired
                    }).ToList()
                })
                .OrderBy(x => x.ComponentName)
                .ToList();
        }

        // ── Toggle expand ──
        private async Task ToggleQuest(int questId)
        {
            if (_expandedQuestIds.Contains(questId))
            {
                _expandedQuestIds.Remove(questId);
            }
            else
            {
                _expandedQuestIds.Add(questId);
                if (!_itemsPerQuest.ContainsKey(questId))
                    await LoadItemsForQuest(questId);
            }
            StateHasChanged();
        }

        private void SetView(string view)
        {
            _view = view;
            StateHasChanged();
        }

        // ── Filter items within a location ──
        private List<SearchInventoryResponseModel> FilterItems(
            List<SearchInventoryResponseModel> items, int questId)
        {
            var search = _searchPerQuest.GetValueOrDefault(questId, string.Empty);
            if (string.IsNullOrWhiteSpace(search)) return items;
            return items
                .Where(x => x.ComponentName.Contains(search, StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        // ── Inline quantity ──
        private async Task IncrementQuantity(SearchInventoryResponseModel item)
        {
            item.AmountAquired++;
            await SaveQuantity(item);
        }

        private async Task DecrementQuantity(SearchInventoryResponseModel item)
        {
            if (item.AmountAquired <= 0) return;
            item.AmountAquired--;
            await SaveQuantity(item);
        }

        private async Task SaveQuantity(SearchInventoryResponseModel item)
        {
            var model = new InventoryCrudModel
            {
                Id = item.Id,
                ComponentId = item.ComponentId,
                AmountAquired = item.AmountAquired
            };
            await InventoryService.UpdateInventory(model, appCancellation.Token);
            BuildAggregated();
            StateHasChanged();
        }

        // ── Quest modals ──
        private Task OpenCreateQuestModal() => OpenQuestModal(null, FormModeEnum.Create);
        private Task OpenEditQuestModal(SearchQuestsResponseModel quest) => OpenQuestModal(quest, FormModeEnum.Update);
        private Task OpenDeleteQuestModal(SearchQuestsResponseModel quest) => OpenQuestModal(quest, FormModeEnum.Delete);

        private async Task OpenQuestModal(SearchQuestsResponseModel? quest, FormModeEnum mode)
        {
            var model = quest != null
                ? await QuestService.GetQuest(quest.Id, appCancellation.Token)
                : new QuestModel { GameSaveId = GameSaveState.ActiveGameSaveId!.Value };

            var parameters = new DialogParameters<EditQuestModal>
            {
                { x => x.Model, model },
                { x => x.FormMode, mode }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditQuestModal>(mode.ToString(), parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled)
            {
                _quests = new();
                _itemsPerQuest = new();
                _expandedQuestIds = new();
                _aggregated = new();
                await LoadQuests();
            }
        }

        // ── Item modals ──
        private Task OpenAddItemModal(SearchQuestsResponseModel quest) =>
            OpenItemModal(null, quest, FormModeEnum.Create);

        private Task OpenEditItemModal(SearchInventoryResponseModel item) =>
            OpenItemModal(item, null, FormModeEnum.Update);

        private Task OpenDeleteItemModal(SearchInventoryResponseModel item) =>
            OpenItemModal(item, null, FormModeEnum.Delete);

        private async Task OpenItemModal(
            SearchInventoryResponseModel? item,
            SearchQuestsResponseModel? quest,
            FormModeEnum mode)
        {
            var model = item != null
                ? await InventoryService.GetInventory(item.Id, appCancellation.Token)
                : new InventoryModel { QuestId = quest!.Id };

            var parameters = new DialogParameters<EditInventoryItemModal>
            {
                { x => x.Model, model },
                { x => x.FormMode, mode }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditInventoryItemModal>(mode.ToString(), parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled && model.QuestId > 0)
            {
                // Refresh just the affected quest
                _itemsPerQuest.Remove(model.QuestId);
                await LoadItemsForQuest(model.QuestId);
                BuildAggregated();
                StateHasChanged();
            }
        }
    }
}