// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using MudBlazor;
using ResourceTrackerUI.Application.Interfaces;
using ResourceTrackerUI.Application.Services.Common;
using ResourceTrackerUI.Components.PageComponents.feature;
using ResourceTrackerUI.Components.PageComponents.feature.Inventory;
using ResourceTrackerUI.Domain.Enums;
using ResourceTrackerUI.Domain.Models.Feature;
using ResourceTrackerUI.Domain.Models.Feature.Inventory;
using ResourceTrackerUI.Domain.Models.Feature.Quest;

namespace ResourceTrackerUI.Pages.feature
{
    public partial class Inventory
    {
        [Inject] private IQuestService QuestService { get; set; }
        [Inject] private IInventoryService InventoryService { get; set; }
        [Inject] private IDialogService DialogService { get; set; }
        [Inject] private ISnackbar Snackbar { get; set; }
        [Inject] private GameSaveState GameSaveState { get; set; }

        // ── View state ──
        private string _view = "location";
        private bool _isLoading = false;
        private string _aggregateSearch = string.Empty;

        // ── Data ──
        private List<SearchQuestsResponseModel> _quests { get; set; } = new List<SearchQuestsResponseModel>();
        private Dictionary<int, List<SearchInventoryResponseModel>> _itemsPerQuest = new();
        private Dictionary<int, string> _searchPerQuest = new();

        // Aggregated view
        private List<AggregatedInventoryItem> _aggregated = new();
        private int _totalItemsLoaded => _itemsPerQuest.Values.Sum(x => x.Count);

        private IEnumerable<AggregatedInventoryItem> FilteredAggregated =>
            string.IsNullOrWhiteSpace(_aggregateSearch)
                ? _aggregated
                : _aggregated.Where(x =>
                    x.ComponentName.Contains(_aggregateSearch, StringComparison.OrdinalIgnoreCase) ||
                    x.ComponentType.Contains(_aggregateSearch, StringComparison.OrdinalIgnoreCase));

        protected override async Task OnInitializedAsync()
        {
            if (!GameSaveState.HasActiveSave) return;
            await LoadQuests();
        }

        private async Task LoadQuests()
        {
            _isLoading = true;

            var response = await QuestService.SearchQuest(new SearchQuestsQueryModel
            {
                GameSaveId = GameSaveState.ActiveGameSaveId,
                PageSize = int.MaxValue,
                OrderBy = "Id"
            }, appCancellation.Token);

            _quests = response.Data.ToList();

            // Init search dict for each quest
            foreach (var q in _quests)
                _searchPerQuest.TryAdd(q.Id, string.Empty);

            _isLoading = false;
        }

        // Loads every quest's items for the aggregate totals view
        private void LoadAllItemsForAggregate()
        {
            BuildAggregated();
            StateHasChanged();
        }

        private void BuildAggregated()
        {
            _aggregated = _itemsPerQuest
                .SelectMany(kvp => kvp.Value.Select(item => new { QuestId = kvp.Key, Item = item }))
                .GroupBy(x => x.Item.Id)
                .Select(g => new AggregatedInventoryItem
                {
                    ComponentId = g.Key,
                    ComponentName = g.First().Item.ComponentName,
                    ComponentType = g.First().Item.ComponentTypeName,
                    ComponentImageUrl = g.First().Item.ComponentImageUrl,
                    TotalQuantity = g.Sum(x => x.Item.AmountAquired),
                    Locations = g.Select(x => new AggregatedLocation
                    {
                        QuestId = x.QuestId,
                        QuestName = _quests.FirstOrDefault(q => q.Id == x.QuestId)?.Name ?? "",
                        Quantity = x.Item.AmountAquired
                    }).ToList()
                })
                .OrderBy(x => x.ComponentName)
                .ToList();
        }


        private void SetView(string view)
        {
            _view = view;
            StateHasChanged();
        }


        // ── Quest modals ──
      
        private async Task OpenCreateQuestModal()
        {
            var model = new QuestModel { GameSaveId = GameSaveState.ActiveGameSaveId!.Value };

            var parameters = new DialogParameters<EditQuestModal>
            {
                { x => x.Model, model },
                { x => x.FormMode, FormModeEnum.Create }
            };

            var options = new DialogOptions { CloseOnEscapeKey = true, FullWidth = true };
            var dialog = await DialogService.ShowAsync<EditQuestModal>(FormModeEnum.Create.ToString(), parameters, options);
            var result = await dialog.Result;

            if (!result.Canceled)
            {
                _quests = new();
                _itemsPerQuest = new();
                _aggregated = new();
                await LoadQuests();
            }
        }

        private void QuestDataUpdate(QuestUpdatedModel model)
        {
            switch(model.UpdateType)
            {
                case QuestUpdateTypeEnum.InitiatedQuestItems:
                    if(!_itemsPerQuest.ContainsKey(model.QuestId))
                    {
                        _itemsPerQuest.Add(model.QuestId, model.Items);
                    }
                    break;
                case QuestUpdateTypeEnum.QuestDeleted:
                    _itemsPerQuest.Remove(model.QuestId);
                    var questToRemove = _quests.FirstOrDefault(q => q.Id == model.QuestId);
                    if (questToRemove != null)
                        _quests.Remove(questToRemove);
                    break;
                case QuestUpdateTypeEnum.ItemsUpdated:
                    _itemsPerQuest[model.QuestId] = model.Items;
                    break;
            }
            LoadAllItemsForAggregate();
            StateHasChanged();
        }

    }
}