<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.3" />
    <PackageReference Include="Microsoft.JSInterop" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResourceTrackerUI.ApiClient\ResourceTrackerUI.ApiClient.csproj" />
    <ProjectReference Include="..\ResourceTrackerUI.Domain\ResourceTrackerUI.Domain.csproj" />
  </ItemGroup>

</Project>
